---
title: "Supplemental_Figure_1"
date: "2024-10-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      fig.width = 15,
                      fig.height = 7)

source('../libraries.R')


```

# Supplemental Figure 1b

```{r}

sfigure_1_b_MCF7 <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1b_MCF7') %>% 
    mutate(celltype = 'MCF-7')
sfigure_1_b_U2OS <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1b_U2OS') %>% 
    mutate(celltype = 'U2OS')
sfigure_1_b_RPE1 <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1b_RPE-1') %>% 
    mutate(celltype = 'RPE-1')

sfigure_1_b <- rbind(sfigure_1_b_MCF7, rbind(sfigure_1_b_U2OS, sfigure_1_b_RPE1))


sfigure_1_b$celltype <- factor(sfigure_1_b$celltype, levels = c("MCF-7", "U2OS", "RPE-1"))

ggplot(sfigure_1_b, aes(x=peakpair_distance)) + geom_density() + 
	labs(y = "Density", 
	     x ="TSS_fwd - TSS_rev in bp") +
    facet_grid(.~celltype, scales = 'free' ) +
	theme_classic() +
    theme(axis.title.x = element_text(size = 16),
													axis.title.y = element_text(size = 16),
													axis.text.x = element_text(size = 16),
													axis.text.y = element_text(size = 16))

```


```{r}
ggplot(sfigure_1_b, aes(x=peakpair_distance)) + geom_density() + 
	labs(y = "Density", 
	     x ="TSS_fwd - TSS_rev in bp",
	     title = 'joint') +
	theme_classic() +
    theme(axis.title.x = element_text(size = 16),
													axis.title.y = element_text(size = 16),
													axis.text.x = element_text(size = 16),
													axis.text.y = element_text(size = 16),
          plot.title = element_text(hjust = 0.5))
```

# Supplemental Figure 1c

```{r}
sfigure_1_c_MCF7 <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1c_MCF7') %>% 
    mutate(celltype = 'MCF-7')
sfigure_1_c_U2OS <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1c_U2OS') %>% 
    mutate(celltype = 'U2OS')
sfigure_1_c_RPE1 <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1c_RPE-1') %>% 
    mutate(celltype = 'RPE-1')

sfigure_1_c <- rbind(sfigure_1_c_MCF7, rbind(sfigure_1_c_U2OS, sfigure_1_c_RPE1))

sfigure_1_c$celltype <- factor(sfigure_1_c$celltype, levels = c("MCF-7", "U2OS", "RPE-1"))

ggscatter(
		sfigure_1_c,
		x = "first_peak",
		y = "second_peak",
		cor.coef = FALSE,
		conf.int = FALSE,
		cor.method = "spearman",
		color = "#b8b8b7",
		alpha = 0.7,
		# cor.coef.coord = c(0.5,-5.7),
		# cor.coeff.args = list(color = "#899da4"),
		size = 1.5,
		# cor.coef.size = 5
	) +
	geom_smooth(method = lm, colour = "#899da4") +
	stat_quadrant_counts(color = "#899da4", size = 5.5) +
	geom_hline(yintercept = 0,
						 colour = "#899da4",
						 alpha = 0.7) +
	stat_cor(method ="spearman", color = "#899da4", label.x = -2.8, label.y = -5.35, size = 5.5) +
	geom_vline(xintercept = 0,
						 colour = "#899da4",
						 alpha = 0.7) +
	labs(x = expression(paste("TSS#1(Log"[2], "FC)")),
			 y = expression(paste("TSS#2(Log"[2], "FC)"))) +
    facet_grid(.~celltype, scales = "free") +
	#scale_x_continuous(breaks = seq(-4, 8, by =2))+
	#scale_y_continuous(breaks = seq(-4, 8, by =2))+
	# scale_x_continuous(limits = c(-6, 8)) +
	# scale_y_continuous(limits = c(-6, 8)) +
	theme_classic() + theme(
		# panel.grid.major = element_line(),
		axis.title.x = element_text(size = 16),
		axis.title.y = element_text(size = 16),
		axis.text.x = element_text(size = 18),
		axis.text.y = element_text(size = 18)
	) +
    geom_density_2d(size = 1, colour = "#899da4")

```

# Supplemental Figure 1d


```{r}

sfigure_1_d_MCF7 <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1d_MCF7') %>% 
    mutate(celltype = 'MCF-7')
sfigure_1_d_U2OS <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1d_U2OS') %>% 
    mutate(celltype = 'U2OS')
sfigure_1_d_RPE1 <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1d_RPE-1') %>% 
    mutate(celltype = 'RPE-1')

sfigure_1_d <- rbind(sfigure_1_d_MCF7, rbind(sfigure_1_d_U2OS, sfigure_1_d_RPE1))
sfigure_1_d$celltype <- factor(sfigure_1_d$celltype, levels = c("MCF-7", "U2OS", "RPE-1"))

ggplot(sfigure_1_d, aes(x=promoterPair_dist)) + geom_density() + 
	labs(y = "Density", 
	     x ="Distance between bidirectional promoters in bp") +
    facet_grid(.~celltype, scales = 'free' ) +
	theme_classic() +
    theme(axis.title.x = element_text(size = 16),
													axis.title.y = element_text(size = 16),
													axis.text.x = element_text(size = 16),
													axis.text.y = element_text(size = 16))

```


```{r}
ggplot(sfigure_1_d, aes(x=promoterPair_dist)) + geom_density() + 
	labs(y = "Density", 
	     x ="Distance between bidirectional promoters in bp",
	     title = 'joint') +
	theme_classic() +
    theme(axis.title.x = element_text(size = 16),
													axis.title.y = element_text(size = 16),
													axis.text.x = element_text(size = 16),
													axis.text.y = element_text(size = 16),
          plot.title = element_text(hjust = 0.5))
```


# Supplemental Figure 1e

```{r}
sfigure_1_e <- read_excel("Source_Data_Extended_Data_Figure_1.xlsx", sheet = 'ExtDataFig1e')

ggplot(sfigure_1_e,
       aes(
           x = peak_number,
           y = readcount,
           color = peak_number,
           fill = peak_number
       )) +
    geom_violin(alpha = 0.4, adjust = 4) +
    ylab("Read count") + xlab("") +
    geom_boxplot(
        aes(x = peak_number, y = readcount),
        outlier.shape = NA,
        alpha = 0.3,
        width = 0.1
    ) +
    facet_wrap( ~ celltype, labeller = as_labeller(c(
        a_MCF7 = "MCF-7",
        b_U2OS = "U2OS",
        c_RPE1 = "RPE-1"
    ))) +
    scale_fill_manual(values = c("#b8b8b7", "#899DA4", "#b8b8b7", "#b8b8b7")) +
    scale_colour_manual(values = c("#b8b8b7", "#899DA4", "#b8b8b7", "#b8b8b7")) +
    scale_y_log10(labels = scales::comma) +
    theme_classic() + theme(
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18, vjust = -4),
        axis.text.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),
        strip.text = element_text(size = 16, face = "bold"),
        strip.background = element_blank(),
        legend.position = 'none',
        axis.ticks.x = element_blank()
    )

```

